base_url = "https://web.stanford.edu/~srliu/PSNotes"
compile_sass = true
title = "Shurui's Notes"
description = "Personal Notes"
taxonomies = [
  { name = "tags", paginate_by = 10, rss = true }
]
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"
external_links_target_blank = true
smart_punctuation = true

[extra]
tikzjax = true
upload_prefix = "/upload"

[extra.booktheme]
home_url="https://shurui.people.stanford.edu/"
book_number_chapters = false
book_only_current_section_pages = false #Set to false, if you want to use hotkey 'c' to toggle this
