name = "MATbook"
description = "A zola book theme inspired from book and olivine"
license = "MIT"
# homepage = "https://github.com/getzola/"
# min_version = ""
# demo = ""

[extra]
book_number_chapters = true
book_only_current_section_pages = false

[author]
name = "Shurui Liu"
homepage = "https://shurui.people.stanford.edu/"
