name = "MATbook"
description = "A zola chapter book theme inspired from book and olivine"
license = "MIT"
homepage = "https://github.com/srliu3264/MATbook"
min_version = "v1.0"
demo = "https://srliu3264.github.io/MATbook-live-demo/"



[author]
name = "Shurui Liu"
homepage = "https://shurui.people.stanford.edu/"
